### ISSUE TITLE
Update mu2etools for AL9

### ISSUE THREAD

**Issue by kutschke** [Mu2e/mu2etools#1]
This was originally reported by Michael Hedges on:

        https://mu2e.slack.com/archives/C72755LAE/p1717507096843589

On AL9 I did  `mu2einit` and  `muse setup`.  After that I tried `setup mu2etools` and get the following message

```
Error: FHICLCPP package must be set up before mu2etools.
Setup a Mu2e Offline version you intend to use and try again.
Error 1 while sourcing /cvmfs/mu2e.opensciencegrid.org/artexternals/mu2etools/v4_04_00/ups/customSetup.sh
```

The hack to get around this is to do the following before you do "setup mu2etools": 

`  export FHICLCPP_VERSION="v4_18_03"`

I believe that any version greater than v4_12_02 will work.  

Probably the easiest way to proceed is to modify customSetup.sh to test for AL9 and take the branch that chooses  fhicl-get.

For a while we need to keep this in UPS in case people want to use older code inside an sl7 container.   When we get to spack phase 3 we can evaluate if we want to spackify it or deploy it some other way.

**Comment by kutschke** [comment]
@rlcee @mhedges You may wish to watch and/or participate in this issue.  If you sign up as a watcher on the repo you will see all of the traffic.  I am not aware of a way to sign up to be a watcher on just this issue.

**Comment by gaponenko** [comment]
@rlcee  Hi Ray, what environment variable do you recommend using for AL9 detection (after "muse setup")?

**Comment by rlcee** [comment]
> @rlcee Hi Ray, what environment variable do you recommend using for AL9 detection (after "muse setup")?

MU2E_OSNAME  will be "sl7" or "al9"
if you need to do this outside of mu2einit, we've been told to use /etc/os-release

**Comment by rlcee** [comment]
> > @rlcee Hi Ray, what environment variable do you recommend using for AL9 detection (after "muse setup")?
> 
> MU2E_OSNAME will be "sl7" or "al9" if you need to do this outside of mu2einit, we've been told to use /etc/os-release

That's set in mu2einit.  After muse setup. MUSE_FLAVOR will be set the same

**Comment by kutschke** [comment]
@rlcee is there a natural place to add this on the wiki?

**Comment by gaponenko** [comment]
This is resolved in mu2etools v4_05_00
